codestates-seb/seb39_main_040

client/package-lock.json
client/package.json
client/src/components/cafe/CafeItem.jsx
client/src/components/login/LoginForm.jsx
client/src/components/login/SignUpForm.jsx
client/src/components/mypage/ReviewItem.jsx
client/src/components/mypage/myPageDetailTab/MyPageInfoTab.jsx
client/src/components/mypage/myPageDetailTab/MyPageReviewTab.jsx
client/src/components/mypage/myPageDetailTab/MyPageWishTab.jsx
client/src/components/ui/Header.jsx
client/src/components/ui/MainTitle.jsx
client/src/components/ui/myPageTab/MyPageTab.jsx
client/src/components/ui/myPageTab/MyPageTabContent.jsx
client/src/pages/Login.jsx
client/src/pages/Mypage.jsx
client/src/pages/SignUp.jsx
client/src/styles/GlobalStyle.jsx

[FE] 마이페이지, 로그인, 회원가입 페이지 마크업

---

client/src/components/cafe/CafeItem.jsx
client/src/components/cafe/cafeDetailTab/CafeDetailTab.jsx
client/src/components/cafe/cafeDetailTab/CafeImagesTab.jsx
client/src/components/cafe/cafeDetailTab/CafeInfo.jsx
client/src/components/cafe/cafeDetailTab/CafeReviewImage.jsx
client/src/components/cafe/cafeDetailTab/CafeReviewItem.jsx
client/src/components/cafe/cafeDetailTab/CafeReviewsTab.jsx
client/src/components/review/EditImageUpload.jsx
client/src/components/review/EditReviewForm.jsx
client/src/components/review/NewImageUpload.jsx
client/src/components/review/NewReviewForm.jsx
client/src/components/review/NewTagForm.jsx
client/src/components/review/StarRating.jsx
client/src/components/ui/cafeTab/CafeTab.jsx
client/src/components/ui/cafeTab/CafeTabContent.jsx
client/src/pages/CafePage.jsx
client/src/pages/EditReviewPage.jsx
client/src/pages/MainPage.jsx
client/src/pages/NewReviewPage.jsx
client/src/styles/GlobalStyle.jsx

(#61)FEAT: 리뷰추가기능 구현(1)

---

client/src/App.jsx
client/src/components/mypage/myPageDetailTab/MyPageInfoTab.jsx
client/src/pages/Login.jsx
client/src/pages/UserUpdate.jsx

- 유저 정보 수정 페이지 마크업
- 사진 업로드 기능 구현
- 로그인 페이지 구현 완료

[FE] 유저수정페이지 마크업 & 로그인 페이지 수정

---

client/src/App.jsx

(#64)FEAT: 리뷰추가기능 수정-라우터연결

---

server/build.gradle
server/src/main/generated/seb39_40/coffeewithme/user/mapper/UserMapperImpl.java
server/src/main/java/seb39_40/coffeewithme/CoffeewithmeApplication.java
server/src/main/java/seb39_40/coffeewithme/common/exeption/ErrorResponse.java
server/src/main/java/seb39_40/coffeewithme/jwt/AuthenticationFailureHandler.java
server/src/main/java/seb39_40/coffeewithme/jwt/AuthenticationSuccessHandler.java
server/src/main/java/seb39_40/coffeewithme/jwt/CorsConfig.java
server/src/main/java/seb39_40/coffeewithme/jwt/CustomAuthenticationFilter.java
server/src/main/java/seb39_40/coffeewithme/jwt/CustomAuthenticationProvider.java
server/src/main/java/seb39_40/coffeewithme/jwt/CustomAuthorizationFilter.java
server/src/main/java/seb39_40/coffeewithme/jwt/CustomUserDetails.java
server/src/main/java/seb39_40/coffeewithme/jwt/CustomUserDetailsService.java
server/src/main/java/seb39_40/coffeewithme/jwt/JwtProvider.java
server/src/main/java/seb39_40/coffeewithme/jwt/SecurityConfig.java
server/src/main/java/seb39_40/coffeewithme/user/controller/UserController.java
server/src/main/java/seb39_40/coffeewithme/user/domain/Like.java
server/src/main/java/seb39_40/coffeewithme/user/domain/User.java
server/src/main/java/seb39_40/coffeewithme/user/dto/UserRequestDto.java
server/src/main/java/seb39_40/coffeewithme/user/dto/UserResponseDto.java
server/src/main/java/seb39_40/coffeewithme/user/mapper/UserMapper.java
server/src/main/java/seb39_40/coffeewithme/user/repository/UserRepository.java
server/src/main/java/seb39_40/coffeewithme/user/service/UserService.java
server/src/main/resources/application.yml

회원 관련 기본적인 회원 가입, 로그인, 정보 조회 기능 구현 완료

회원 기능 1차 구현 완료

---

client/src/components/mypage/myPageDetailTab/MyPageWishTab.jsx
client/src/components/ui/cafeTab/CafeTabContent.jsx
client/src/components/ui/myPageTab/MyPageTabContent.jsx
client/src/pages/CafeDetail/CafeInfoPage.jsx
client/src/pages/MainPage.jsx

(#69)refactor: 프로젝트 파일 리팩토링(2)

---

client/.gitignore
client/src/App.jsx
client/src/components/cafe/CafePageTopSection/index.jsx
client/src/components/common/Title.jsx
client/src/pages/CafeDetail/CafeMenuPage.jsx
client/src/pages/CafeDetail/CafeReviewPage.jsx
client/src/pages/LoginPage.jsx
client/src/pages/SignUpPage.jsx

(#13)feat:전역관리

---

client/src/components/common/MiddleTitle.jsx
client/src/pages/LoginPage.jsx
client/src/pages/SignUpPage.jsx
client/src/pages/User/UserInfoPage.jsx

[FE] 중간 제목 컴포넌트 구현

---

client/src/App.jsx
client/src/components/cafe/CafeCard.jsx
client/src/components/review/ReviewForm.jsx
client/src/components/review/ReviewImageUpload.jsx
client/src/pages/CafeDetail/CafeDetailPage.jsx
client/src/pages/CafeDetail/CafeMenuPage.jsx
client/src/pages/MainPage.jsx
client/src/pages/Review/NewReviewPage.jsx
client/src/store/cafe.jsx

feat: 리뷰작성 페이지 수정

---

client/src/components/common/Header.jsx
client/src/pages/LoginPage.jsx
client/src/pages/SignUpPage.jsx
client/src/store/useAuth.jsx

- 회원가입 기능을 구현했습니다.
- 로그인 기능을 구현했습니다.

[FE] 회원가입, 로그인 기능 구현

---

client/public/index.html
client/src/App.jsx
client/src/pages/User/UserInfoEditPage.jsx
client/src/pages/User/UserInfoPage.jsx
client/src/pages/User/UserReviewPage.jsx
client/src/pages/User/UserWishPage.jsx

- 로그인한 유저는 자신의 정보를 "나의 정보" 페이지에서 조회할 수 있습니다.
- 로그인한 유저는 자신의 정보를 수정할 수 있습니다.

[FE] 유저 정보 조회& 수정 기능 구현

---

client/src/App.jsx
client/src/components/cafe/CafeCards.jsx

app.js, CafeCards.js파일 충돌 에러 수정

feat:충돌에러파일 수정

---

client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCard.jsx
client/src/components/common/TabBar.jsx
client/src/components/review/NewReviewForm.jsx
client/src/components/review/ReviewImageUpload.jsx
client/src/pages/CafeDetail/CafeDetailPage.jsx

(#100)feat: 이미지첨부 기능구현-1

---

client/src/store/useLoginStore.jsx

[FE] 로그인 상태 저장명 변경

---

client/src/components/review/NewReviewForm.jsx

(#100)feat: 이미지첨부기능구현

---

server/src/main/java/seb39_40/coffeewithme/exception/ExceptionCode.java
server/src/main/java/seb39_40/coffeewithme/jwt/CustomAuthorizationFilter.java
server/src/main/java/seb39_40/coffeewithme/jwt/JwtProvider.java
server/src/main/java/seb39_40/coffeewithme/review/repository/ReviewRepository.java
server/src/main/java/seb39_40/coffeewithme/user/controller/UserController.java
server/src/main/java/seb39_40/coffeewithme/user/domain/User.java
server/src/main/java/seb39_40/coffeewithme/user/dto/UserReviewResponseDto.java
server/src/main/java/seb39_40/coffeewithme/user/dto/WishlistResponse.java
server/src/main/java/seb39_40/coffeewithme/user/mapper/UserMapper.java
server/src/main/java/seb39_40/coffeewithme/user/repository/LikeRepository.java
server/src/main/java/seb39_40/coffeewithme/user/service/UserService.java

[BE] 인증 관련 코드 수정

---

server/src/main/java/seb39_40/coffeewithme/cafe/domain/Cafe.java
server/src/main/java/seb39_40/coffeewithme/user/controller/UserController.java
server/src/main/java/seb39_40/coffeewithme/user/dto/UserResponseDto.java
server/src/main/java/seb39_40/coffeewithme/user/dto/UserReviewResponseDto.java
server/src/main/java/seb39_40/coffeewithme/user/dto/WishlistResponse.java
server/src/main/java/seb39_40/coffeewithme/user/mapper/UserMapper.java
server/src/main/java/seb39_40/coffeewithme/user/service/UserService.java

[BE] 마이페이지 리뷰 조회 기능 구현

---

server/src/main/java/seb39_40/coffeewithme/jwt/CustomUserDetailsService.java
server/src/main/java/seb39_40/coffeewithme/jwt/JwtProvider.java
server/src/main/java/seb39_40/coffeewithme/user/dto/UserReviewResponseDto.java
server/src/main/java/seb39_40/coffeewithme/user/mapper/UserMapper.java
server/src/main/resources/application.yml

[BE] 맵퍼 코드 수정

---

server/src/main/java/seb39_40/coffeewithme/jwt/CustomAuthenticationFilter.java
server/src/main/java/seb39_40/coffeewithme/jwt/CustomUserDetailsService.java
server/src/main/java/seb39_40/coffeewithme/user/controller/UserController.java
server/src/main/java/seb39_40/coffeewithme/user/domain/User.java
server/src/main/java/seb39_40/coffeewithme/user/dto/UserRequestDto.java
server/src/main/java/seb39_40/coffeewithme/user/dto/UserResponseDto.java
server/src/main/java/seb39_40/coffeewithme/user/mapper/UserMapper.java
server/src/main/java/seb39_40/coffeewithme/user/service/UserService.java
server/src/main/resources/application.yml
server/src/main/resources/data.sql

[BE] 프로필 이미지 관련 기능 구현

---

client/public/index.html
client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCard.jsx
client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCards.jsx
client/src/components/cafe/CafePageTopSection/CafeInfoMap.jsx
client/src/components/common/ErrorAlert.jsx
client/src/components/common/SuccessAlert.jsx
client/src/components/review/NewReviewForm.jsx

- 이미지 미리보기 기능 구현 및 파일 선택 후 이미지 post 요청 기능 구현

(#110)이미지첨부 미리보기 기능 구현

---

client/src/components/mypage/UserWishCard.jsx
client/src/components/mypage/UserWishCards.jsx

- 방문을 원하는 카페를 찜할 수 있습니다.
- 찜한 카페를 삭제할 수 있습니다.

[FE] 위시리스트 추가/삭제 구현

---

client/public/index.html
client/src/components/cafe/CafePageTopSection/CafeInfoMap.jsx
client/src/components/cafe/CafePageTopSection/index.jsx
client/src/components/review/NewReviewForm.jsx

주소 데이터를 좌표로 변경 후 지도에 마커로 표시하는 기능을 구현함 (카카오맵api)

(#114)feat: 주소를 좌표로 변경해 마커표시 기능구현

---

client/src/api/core.jsx
client/src/components/common/Header.jsx
client/src/pages/User/UserInfoEditPage.jsx
client/src/pages/User/UserInfoPage.jsx

- (로그인한 유저는) 자신의 유저 정보를 수정할 수 있습니다. 
- 자신이 지정한 프로필 사진에 따라 헤더 이미지가 변경됩니다.

[FE] 유저 정보 수정 구현

---

client/src/components/mypage/UserReviewCard.jsx
client/src/components/review/EditReviewForm.jsx
client/src/pages/Review/EditReviewPage.jsx

- 유저는 자신이 작성한 리뷰를 수정, 삭제할 수 있습니다.

[FE] 리뷰 수정&삭제 구현

---

client/src/components/cafe/CafeCards.jsx
client/src/components/common/SearchBar.jsx
client/src/pages/MainPage.jsx
client/src/store/search.jsx

- 검색창에 카페 이름을 입력시 연관된 카페가 검색되어 노출됩니다.

[FE] 메인페이지 검색 기능 구현

---

client/src/components/cafe/CafeCards.jsx
client/src/components/common/FilterBar.jsx
client/src/pages/MainPage.jsx

(#113)feat: 카테고리 필터링 기능 구현

---

client/src/App.jsx
client/src/pages/NotFoundPage.jsx

- 404에러페이지 구현 - 정해지지 않은 경로로 이동할 시 에러 페이지 렌더링 됨

(#153)feat: 404에러페이지 구현

---

client/src/components/review/EditReviewForm.jsx
client/src/components/review/NewReviewForm.jsx

(#12)style:이미지첨부 css 수정

---

client/src/components/cafe/CafeCards.jsx

검색, 필터링 후 해당하는 아이템이 없으면 안내창이 뜨도록 만들었음

(#12)style: 안내창추가작업

---

client/src/components/cafe/CafeCard.jsx
client/src/components/cafe/CafeCards.jsx
client/src/components/cafe/CafePageBottomSection/CafeReviews/CafeReviewCards.jsx
client/src/components/cafe/CafePageTopSection/CafeInfoMap.jsx
client/src/components/cafe/CafePageTopSection/index.jsx
client/src/pages/CafeDetail/CafeDetailPage.jsx

(#12)feat&style:데이터조회기능 수정 및 css세부작업

---

client/src/components/cafe/CafeCards.jsx
client/src/components/cafe/CafePageTopSection/index.jsx

- 메인페이지 카페목록 css를 수정했습니다. 
- 로그인 한 유저만 카페 찜하기(위시리스트 추가) 기능을 사용할 수 있도록 알림 및 제한했습니다.

[FE] css 수정 & 로그인 유저 대상으로만 찜하기 기능 사용 제한 

---

client/public/index.html
client/src/styles/GlobalStyle.jsx

(#12)style: 폰트변경

---

client/src/components/cafe/CafePageTopSection/index.jsx

- 인스타그램 주소 및 전화번호 데이터 조회 수정 작업

(#12)feat: 상세데이터 조회 수정

---

server/src/main/java/seb39_40/coffeewithme/security/authentication/AuthenticationFailureHandler.java
server/src/main/java/seb39_40/coffeewithme/security/authentication/AuthenticationSuccessHandler.java
server/src/main/java/seb39_40/coffeewithme/security/authorization/CustomAuthorizationFilter.java
server/src/main/java/seb39_40/coffeewithme/security/jwt/JwtProvider.java
server/src/main/java/seb39_40/coffeewithme/security/jwt/RedisRepository.java
server/src/main/java/seb39_40/coffeewithme/security/userdetails/CustomUserDetailsService.java
server/src/main/resources/application.yml
server/src/main/resources/data.sql

(be) refactoring
